### ISSUE TITLE
Carousel UI구현

### ISSUE THREAD

**Issue by rlaclghks123** [rahee-k-it/react-ui-storybook#16]
## Carousel UI를 만들려고 합니다. 

- [x] `onClickLeft,Right ` :  autoPlay가 false일경우  left,right 아이콘을 나타내며,  click Event를 통해 수동으로 넘김
- [x] `AutoPlay` : boolean으로 true일 경우, setTimeout을 통해 2초마다 자동넘김 (left,right icon 숨김)
- [x] `useState ` : transForm 위치를 state에 저장하여, left, right클릭시 transFormX의 위치를 조절하여 캐러셀 구현
- [x] `childrens` : childrens를 []로 만들었고, 안에 children, img를 통해 배경이미지 및 내용을 넣도록 구현 

현재 children과 친해지지 못해 props로 childrens Obj를 전달하는 방법으로 구현은 했으나, mui처럼 carousel의 children 형태로 집어 넣기위해 고민중입니다.

**Comment by rahee-k-it** [comment]
Carousel UI 기대되네요! children 어렵죠. 그래도 치환님이라면 금방 children과 친해질 거 같습니다. 우리 모두 파이팅합시다!
