### ISSUE TITLE
Carousel-dh  질문

### ISSUE THREAD

**Issue by rlaclghks123** [rahee-k-it/react-ui-storybook#18]
## 대현님께서 작성해주신 코드에서 3가지 질문이 있습니다. 

1. 아래의 코드에서  왜 onClickRight만 useCallback을 사용 하셨는지 궁금합니다. 
```
const onClickLeft = () => {
    const newTranslateXAmount = (translateXAmount + itemWidth) % translateXAmountLimit;

    setTranslateXAmount(
      (newTranslateXAmount > 0 ? -translateXAmountLimit : 0) + newTranslateXAmount,
    );
  };
  
  const onClickRight = useCallback(() => {
    setTranslateXAmount((translateXAmount - itemWidth) % translateXAmountLimit);
  }, [translateXAmount, itemWidth, translateXAmountLimit]);
  ```
  <hr>
2. 아래의 코드에서 children과 Children.toArray(children)은 accordion2에서와 다르게 값이 같은걸로 예상되는데, 사용 이유를 알 수 있을까요? (혹은 값이 다른가요?)

  ```
  const itemCount = Children.toArray(children).length;
  ```
  
  <hr>  
3. 아래의 코드에서 {children} 을 사용하지 않고 {children:child} 를 사용한 이유가 궁금합니다. 

  ```
function CarouselItem({ children: child }) {
  const { itemWidth } = useContext(CarouselContext);
  return <CarouselItemContainer itemWidth={itemWidth}>{child}</CarouselItemContainer>;
}

```

**Comment by daehyun-thevc** [comment]
> 1.아래의 코드에서 왜 onClickRight만 useCallback을 사용 하셨는지 궁금합니다.

그 이유는 useEffect에서 onClickRight를 사용하기 때문입니다. useEffect에서 사용되는 변수나 함수는 dependencies에 명시해 줘야하는데, 이 때 일반 함수라면 매번 렌더링할 때마다 재정의가 되서 useEffect에 등록한 함수가 렌더링 때마다 작동합니다. 그러한 문제를 방지하고자 useCallback을 사용하였습니다.

useCallback을 사용하지 않으면 다음과 같은 오류가 뜹니다.
![image](https://user-images.githubusercontent.com/87633241/185359774-8f2758a2-e225-4b88-9379-81a7aead1316.png)

> 2. 아래의 코드에서 children과 Children.toArray(children)은 accordion2에서와 다르게 값이 같은걸로 예상되는데, 사용 이유를 알 수 있을까요? (혹은 값이 다른가요?)

Carousel을 다음과 같이 활용한다고 가정해 보겠습니다.
```jsx
<Carousel>
  <CarouselItem> ... </CarouselItem>
  {[1,2].map(v => ( <CarouselItem> ... </CarouselItem>))}
</Carousel> 
```
map을 통해서 여러 개의 `<CarouselItem />`을 렌더링할 가능성은 충분히 있습니다.

그러면 children은 아래와 같이 구성됩니다.
```jsx
[<CarouselItem>...</CarouselItem>, [<CarouselItem>...</CarouselItem>,<CarouselItem>...</CarouselItem>]]
```

렌더링 시에는 CarouselItem 3개를 모두 정상적으로 보여주겠지만, children에는 요소가 2개가 뿐입니다.
Children.toArray를 사용하면 flat하게 해줘서 아래와 같이 배열 안의 배열을 벗겨줍니다.
```jsx
[<CarouselItem>...</CarouselItem>, <CarouselItem>...</CarouselItem>,<CarouselItem>...</CarouselItem>]
```

>3. 아래의 코드에서 {children} 을 사용하지 않고 {children:child} 를 사용한 이유가 궁금합니다.

자식은 모두 children이라는 이름으로 받지만, CarouselItem에는 한 개의 요소만 자식으로 들어올 것이라 예상해서 child로 이름을 바꿨습니다. 그런데 지금 생각해보니 여러 개가 들어올 수도 있을 것 같네요. 이 부분은 children 그대로 써도 괜찮을 것 같습니다.

**Comment by rlaclghks123** [comment]
1,2,3번 모두 이해 완료 했습니다! 
2번의 경우 전혀 생각하지 못했었네요. 감사합니다.
