### ISSUE TITLE
Warning: ReactDOM.render is no longer supported in React 18. Use createRoot instead. Until you switch to the new API, your app will behave as if it's running React 17.    Warning 문제 발생 

### ISSUE THREAD

**Issue by rlaclghks123** [rahee-k-it/react-ui-storybook#19]
## 계속 발생하는 Warning 문제,  해결 해볼려고 했으나 실패

- 처음엔 나타나지 않지만, 새로고침하면 warning이 나타남
- npm start를 통한 create-react-app은 warning이 나타나지 않지만, storybook에는 warning이 나타남.
-코드 수정후 storybook 창을닫고, npm run storybook을 통해 재실행해서 새로고침해도 나타남.
- 아래의 사진에 있는 버튼을 통해 warning을 지운뒤 새로고침 해도 계속 나타남
![스크린샷 2022-08-18 오후 5 31 24](https://user-images.githubusercontent.com/55423198/185348958-24afdf3f-c284-4c14-8a14-afb1cd1fc3e4.jpg)

  # 현재 Develop 브랜치의 index.js

- 참고 : https://velog.io/@citron03/React-18%EC%97%90%EC%84%9C-ReactDOM.render%EC%99%80-createRoot

![스크린샷 2022-08-18 오후 5 20 08](https://user-images.githubusercontent.com/55423198/185346533-d391e7bf-350a-47f9-8f4a-7653ccd82f11.jpg)

  # 1차시도 - 실패

- 참고 : https://dev.to/osmanforhad/react-js-warning-reactdomrender-is-no-longer-supported-in-react-18-use-createroot-instead-until-you-switch-to-the-new-api-1jhh

   ![스크린샷 2022-08-18 오후 5 11 51](https://user-images.githubusercontent.com/55423198/185344753-6ec79b7a-b78d-4755-8515-304adecc41c2.jpg)

# 2차시도 - 실패

- 참고 : https://7357.tistory.com/m/44 
   ![스크린샷 2022-08-18 오후 5 14 33](https://user-images.githubusercontent.com/55423198/185345360-4b9a473a-fa3e-435a-bb40-bc40834f8822.jpg)
   
# 3차시도 -실패
- 총 4가지 해결책이 있는데, 마지막 4번째 17버전으로 Downgrade빼고 다 실패했으며, 4번째는 시도하지 않음

- 참고 https://exerror.com/warning-reactdom-render-is-no-longer-supported-in-react-18-use-createroot-instead-until-you-switch-to-the-new-api-your-app-will-behave-as-if-its-running-react-17/

**Comment by daehyun-thevc** [comment]
아 이거 저번에 제가 해결해야 할 것 같다고 말씀드렸죠. 죄송합니다 제가 좀만 더 알아봤으면 저희가 해결할 수 없는 문제라고 말씀을 드렸을 텐데 그리하지 못해 치환님께서 고생하신 것 같습니다.
이건 외부 라이브러리에서 사용하는 react가 구 버전이라서 이런 문제가 발생하는 것입니다. 보시면 아래와 같이 어디에서 문제가 발생했는지 보실 수 있는데요.
![image](https://user-images.githubusercontent.com/87633241/185363481-ab8ebe38-ad5a-4c1e-855d-947436c7e61d.png)
storybook addon action manager라는 곳에서 발생함을 확인할 수 있습니다. 스토리북 라이브러리가 자체적으로 가지고 있는 문제이기 때문에 저희가 해결할 수 있는 부분이 아니니 무시하고 넘어가도 좋을 것 같습니다.

**Comment by rlaclghks123** [comment]
아하! 넵 알겠습니다. 감사합니다
