### ISSUE TITLE
프로그레스 바(Progress Bar) UI 구현

### ISSUE THREAD

**Issue by jinyoung4478** [rahee-k-it/react-ui-storybook#31]
#### feature/progress 브랜치에서 프로그레스바 UI를 다음과 같이 개발하려고합니다.

> #### Controls addon
`value` : 프로그레스바 진행 정도를 조절하는 값
`isValue` : 프로그레스바 진행률 표시 여부
`bgColor` : 프로그레스바 색상
`size` : 프로그레스바의 height를 이용한 크기 조절
`borderRadius` : 프로그레스바 border-radius 설정
`label` : label의 텍스트 지정
`isLabel` : 프로그레스바에 대한 정보를 나타내는 텍스트 설정 여부

<hr>

#### 특이 사항
 bgColor의 옵션에 관련하여 common.js의 backgroundColors이 아닌 커스텀하여 만든 옵션들을 사용할 예정입니다. transparent처럼 사용하지 못하거나 혹은 어울리지 않는 색상의 option들이 많기 때문입니다.

**Comment by daep93** [comment]
진영님, 32가지 UI에 스크롤 바가 없던데 혹시 다른 UI에 적용하기 위해 만드시는 것일까요?

**Comment by jinyoung4478** [comment]
> 진영님, 32가지 UI에 스크롤 바가 없던데 혹시 다른 UI에 적용하기 위해 만드시는 것일까요?

아... 프로그레스 입니다
