### ISSUE TITLE
Card feature

### ISSUE THREAD

**Issue by rahee-k-it** [rahee-k-it/react-ui-storybook#4]
**card UI 생성 예정**

basic card를 기본으로 만들것이고,  props를 조정하여 color card, border card, shadow card를 만들어 스토리북에서 사용자가 직관적으로 card UI를 확인할 수 있도록 할 생각입니다.

**Comment by rlaclghks123** [comment]
Card폴더명을 card로 바꿔주시면 좋을 것 같습니다!

**Comment by rahee-k-it** [comment]
![image](https://user-images.githubusercontent.com/108662234/183550623-383469f3-edef-4773-bfc0-955c97c6c0f2.png)
치환님이 말씀하신 Card 폴더명이 위 사진 속의 폴더명일까요?

**Comment by rlaclghks123** [comment]
저한테는 Card로 보입니다 ㅠㅠ 혹시 저번에 대현님께서 말씀해주신 방법으로 바꾸셨나요?
![스크린샷 2022-08-09 오전 11 35 59](https://user-images.githubusercontent.com/55423198/183551525-c09de6c3-3266-499b-8857-364c07882b62.jpg)

**Comment by rahee-k-it** [comment]
Accordion UI 수정하면서 feature/accordion 브랜치에서 피드백 반영하였습니다. 터미널에 git config core.ignorecase false 명령어 넣어 git이 대소문자 인식하도록 하였습니다. 지난번에 손으로 명령어 적다가 온점 사이에 띄어쓰기를 했었나봐요,,,😅 항상 결과까지 꼼꼼히 봐야겠습니다!
