### ISSUE TITLE
common.js파일 만들기전 Test결과 문제발생

### ISSUE THREAD

**Issue by rlaclghks123** [rahee-k-it/react-ui-storybook#5]
## 구현
1. common.js에 TextColor 작성
2. Proptype 지정   color: PropTypes.oneOf(Object.keys(TextColor)),

## 문제발생
1. PropTypes를 줬으나, common.js에 넣은값은 나타나지 않고, 1~21까지 숫자만 나타나며, 값은 color:t 이런식으로 나타남. 
조합해보면 Object keys TextColor 로 나타납니다. 

## 디버깅(?) 시도
1. color:Proptypes.string 으로 한뒤, TextColor의 key값을 전달해주면 작동합니다. 

## 사진첨부 

![스크린샷 2022-07-28 오후 1 48 53](https://user-images.githubusercontent.com/55423198/181422921-3362057b-0d5a-4984-a2a3-910fd2883e3b.jpg)

**Comment by daehyun-thevc** [comment]
아 이거  `color: ${TextColor[color]}` 끝에 `;`이 없어서 그럴거에요.

**Comment by daehyun-thevc** [comment]
아 제가 잘못봤네요. 죄송합니다. 음.... rgb안에 콤마가 없어서 그런가 싶네요. 그래도 안되면 다른 브랜치 열어서 upstream 만들어주세요. 제가 확인해볼게요.

**Comment by rlaclghks123** [comment]
혹시 외부에서 받아서 쓰면 작동 안하는거 아닐까요? 

![스크린샷 2022-07-28 오후 3 46 29](https://user-images.githubusercontent.com/55423198/181438988-b94e4a36-c161-43ba-97b5-039e22301ccd.jpg)

**Comment by daehyun-thevc** [comment]
실험해 보니 그런 것 같네요. 색상의 경우에는 props로 제어하지 말고, css에 적어서 className에 추가하는 형식으로 적어야 할 것 같습니다.
왜 외부 파일과 연결이 안 되도록 했을까요...?
