### ISSUE TITLE
common.js 파일

### ISSUE THREAD

**Issue by rlaclghks123** [rahee-k-it/react-ui-storybook#8]
참고: [tailwindcss](https://tailwindcss.com/docs/text-color)

위의 페이지를 참고해서 정했습니다.
- `Color` :  검정, 흰색, 회색, 빨간색, 초록색, 파란색으로 선정
- `FontSize` :  xs,sm,base,lg,xl,2xl    총  6개 선정
- `FontWeight` :  100~900중 홀수로 5개 선정 

![스크린샷 2022-07-29 오후 8 24 51](https://user-images.githubusercontent.com/55423198/181749167-6388760f-ce23-4c11-a47c-c3684672714b.jpg)

**Comment by rahee-k-it** [comment]
테일윈드에서 모든 예시들 확인했습니다! 치환님께서 선정하신 font size도 적절한거 같습니다. 만드느라 고생하셨습니다. 정말 감사합니다!!

**Comment by rlaclghks123** [comment]
네 그럼 develop branch에 push 할게요!

**Comment by rlaclghks123** [comment]
라희님 제가 잘못 생각해서 혼란을 드린 것 같습니다 죄송해요.  bgColor, color가 클래스 이름이 달라서, 따로 작성해야 작동 하는것 같아요 
bgColor 또한 아까 말씀 해주신대로 검 흰 회 빨 초 파로 추가 하겠습니다!  혹시 다른 색상 원하시면 말씀해주세요!

**Comment by daehyun-thevc** [comment]
피드백을 늦게 드려서 죄송합니다. 다 좋은데, export 하는 변수명을 복수형으로 바꾸고 color 부분도 fontColors 라고 바꾸는게 좋을 것 같습니다.
그 부분은 제가 바꾸겠습니다!

**Comment by rlaclghks123** [comment]
넵 감사합니다!

**Comment by daehyun-thevc** [comment]
아 그리고 마지막으로 하나 더 말씀 드리면 변수명을 파스칼 케이스로 적었는데 보통은 컴포넌트에 적는 방식이라 카멜 케이스로 변경하겠습니다.
