### ISSUE TITLE
tailwindcss props 적용 안됨.

### ISSUE THREAD

**Issue by rlaclghks123** [rahee-k-it/react-ui-storybook#9]
## hover 적용이 안됨. 
참고: [tailwindcss](https://tailwindcss.com/docs/text-color#hover-focus-and-other-states)

아래의 3가지 경우로 시도
- `ButtonStyle의 p에 적용`:
 ![image](https://user-images.githubusercontent.com/55423198/182016008-b39af248-4a84-4eaf-96e9-d2825c01f2c6.png)
   결과 : 작동X
   

- `ButtonStyle에 적용`: 
![image](https://user-images.githubusercontent.com/55423198/182016034-706a274f-2665-47b5-85c9-68288a779153.png)
   결과 : 작동X
   
- `ButtonStyle에 prop말고 직접적용`: 
          <img width="487" alt="image" src="https://user-images.githubusercontent.com/55423198/182016091-fa45e62a-3635-4ad9-9a89-a59ddcaf736c.png">
   결과 : 작동 O
   
-  참고로 hover: 대신 group-hover: 또한 적용 해봤으나 작동하지 않았습니다.

## Text Decoration이 1가지만 적용됨 
참고: [tailwindcss](https://tailwindcss.com/docs/text-decoration)

- Default값으로 text-decoration에 underline을 준 뒤 story에서  select option으로   ['underline','no-underline'] 을 주면 작동을 하지만, default값을 주지 않거나 no-underline을 주면 작동하지 않습니다. 

- Default값으로 underline을 주면, underline, no-underline은 작동하지만, overline 이나 line-through는 작동하지 않습니다.
같은 맥락으로 Default값에 line-through를 준다면 line-through와 no-underline은 작동하지만, overline이나 underline은 작동하지 않습니다.

<img width="442" alt="image" src="https://user-images.githubusercontent.com/55423198/182017066-f2ec623c-9387-4178-8a2f-0a6d01abbc1a.png">

**Comment by daehyun-thevc** [comment]
치환님 개발환경에서 확인할 수 있도록 현재 작업하고 있는 브랜치 push 가능할까요?

**Comment by daehyun-thevc** [comment]
우선 코드를 봤는데요. 몇 가지 문제점이 있어서 그것부터 말씀드리겠습니다. 

### 1. undefined 클래스 처리
현재 props로 넘어와서 className으로 들어가는 것들 중에 기본값이 없어서 undefined가 되는 녀석들이 있는데 거기에 대한 처리를 좀 해줘야겠습니다.
![image](https://user-images.githubusercontent.com/87633241/182023986-b1872fe8-48b3-4861-937e-379529c826d1.png)

### 2. 불필요한 props 제거
라희가 하고 있는 카드의 경우 내부적으로 헤더와 컨텐트로 나뉘기 때문에 카드 컴포넌트를 불러와서 사용하는 입장에서 className으로는 둘을 구분해서 bgColor등을 적용할 수가 없습니다. 이럴 경우에는 어쩔 수 없이 컴포넌트 props로 헤더 또는 컨텐트의 bgColor를 바꾸겠다고 넣어줘야겠지만, 버튼 같이 단순한 구성에서는 굳이 그럴 필요가 없습니다. 그럴 경우엔 그냥 버튼을 불러오는 부모 컴포넌트에서 className을 지정해도 됩니다. 이렇게요.
```html
<Button className="bg-red-300 text-green-500" >button</Button>
```
대신 이렇게 하면 Button 컴포넌트 내부적으로 적어둔 className이 덮어 씌워질 수 있으니깐 구조를 아래와 같이 변경해야겠죠?
```jsx
function Button(props) {
  const {
    ...,
    className,
    ...rest
  } = props;

  return (
    <ButtonStyle
      className={`... ${className}`}
      {...rest}
    >
    ...
   )
}
```
이렇게 적게되면 props로 넘겨줬던 대부분의 값들이 더 이상 필요 없어질 것입니다. 

### 3. hover 문제
다시 돌아와서 치환님께서 적어주신 hover 문제가 잘 해결되지 않네요. 동적으로 hover를 바꾸려니 문제가 되는가 싶기도 합니다. 

그런데 이 문제를 해결하기 이전에 굳이 hover의 효과를 props로 바꿀 필요가 있을까 생각을 했습니다. mui처럼 hover 효과를 고정해서 넣어줘도 되지 않을까요?

### 4. text-decoration 문제
tailwind.config.js에 `content`를 아래와 같이 변경하니 정상적으로 잘 작동하네요.
```js
content: ['./src/**/*.jsx', './src/**/*.js'],
```

**Comment by rlaclghks123** [comment]
대현님 여기 2번에서  className앞에 존재하는 ... 부분은 rest의 ...과 달리 그냥 다른 props들을 의미하는 건가요??

**Comment by daehyun-thevc** [comment]
넵, 그냥 생략 표시였습니다.
